# Generated by Django 5.0.6 on 2024-07-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bitcointransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
